Fody/PropertyChanged

PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged/DoNotCheckEqualityAttribute.cs
PropertyChanged/PropertyChanged.csproj
PropertyChangedTests/BaseTaskTests.cs
PropertyChangedTests/PropertyChangedTests.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4Client.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessPhone.csproj
TestAssemblies/AssemblyToProcess/ClassDoNotCheckEquality.cs

In some cases there is a need to raise property change notification on every property update even if the new value equals the old. My patch provides a DoNotCheckEqualityAttribute intended for marking properties that should not be checked for value equality.

Added DoNotCheckEqualityAttribute

---

PropertyChanged.Fody/CecilExtensions.cs
PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChangedTests/BaseTaskTests.cs
TestAssemblies/AssemblyToProcess/ClassDoNotCheckEqualityWholeClass.cs

I have the attribute on a base class and all derived classes should disable equality.

DoNotCheckEquality needs to support "inherited" class attribute

---

PropertyChanged.Fody/CheckForEqualityConfig.cs
PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/PropertyChanged.Fody.csproj
PropertyChangedTests/CheckForEqualityConfigTests.cs
PropertyChangedTests/OnPropertyNameChangedConfigTests.cs
PropertyChangedTests/PropertyChangedTests.csproj

I added the configuration option CheckForEquality which existed in the old NotifyPropertyWeaver and didn't make the transition to PropertyChanged.Fody.
There are some cases where it's more convenient to just ignore the equality check for a whole project instead of setting the DoNotCheckEquality attribute on thousands of properties.
I hope you can merge this back to your main branch so it will be included in future releases.

added configuration option for CheckForEquality

---

PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/SupportsCeqChecker.cs
PropertyChanged.Fody/TypeEqualityFinder.cs
PropertyChangedTests/BaseTaskTests.cs
PropertyChangedTests/EventTester.cs
PropertyChangedTests/Verifier.cs
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4Client.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessPhone.csproj
TestAssemblies/AssemblyToProcess/ClassEqualityWithGenericClassOverload.cs
TestAssemblies/AssemblyToProcess/ClassEqualityWithGenericStructOverload.cs
TestAssemblies/AssemblyToProcess/ClassEqualityWithStruct.cs

PR #164 has tests for this, but the fix was more complex than it needed to be.
Instead `object.Equals()` is enough to call the correct override, making the code we need simpler.
This PR keeps the failing tests from #164 but implements the simpler solution.

Generic types with op_equality overrides fix

---

PropertyChanged.Fody/TypeResolver.cs

Not sure I fully understand _why_ this happens, but I have `NullReferenceExceptions` when building with Fody.
It took some time to figure out this was because the `TypeResolver` returns `null` for a specific type; this PR makes Fody throw an exception with a clear error message if that happens.

Throw an exception if InnerResolve returns null

---

PropertyChanged.Fody/InvokerTypes.cs
PropertyChanged.Fody/MethodFinder.cs
PropertyChanged.Fody/PropertyWeaver.cs
PropertyChangedTests/BaseTaskTests.cs
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4.csproj
TestAssemblies/AssemblyToProcess/AssemblyToProcessDotNet4Client.csproj
TestAssemblies/AssemblyToProcess/ClassWithOnChangedBeforeAfterGeneric.cs

Adds support for calling an `OnPropertyChanged<T>(string propertyName, T before, T after)` method with the type of the property.

Added support for a generic before after call

---

PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/MsCoreReferenceFinder.cs

Changed equality checker code based on the discussion in #191.
- Base types (int, byte, etc.) have been fixed to use `ceq`
- Structs now use `EqualityComparer`
- objects still use `object.Equals`
- if there's an equals method on the type it uses that, so no change there

Equality fixes

---

PropertyChanged.Fody/CheckForEqualityUsingBaseEqualsConfig.cs
PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChangedTests/CheckForEqualityUsingBaseEqualsConfigTests.cs

* When this option is `true` (default), a child class will use the parent's equality check in the event that the parent overrides `==`. 
* When this option is `false`, a child class will use the default equality check (`OpCodes.Ceq`) in the event that the parent overrides `==`.

allow for config option to check equality using base Equals or not

---

PropertyChanged.Fody/TypeEqualityFinder.cs
PropertyChangedTests/AssemblyWithBaseInDifferentModuleTests.cs
TestAssemblies/AssemblyWithBase/BaseWithEquals/BaseClass1.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/BaseWithGenericProperty/Class.cs

Fixed an unhandled exception that occured while weaving, if a property was using a generic type from another assembly that implmented static bool Equals(T,T) or had == overwritten.
See #259 for details.
Basically the issue was that in TypeEqualityFinder.FindNamedMethod a wrong type was passed to MakeGeneric, resulting in a wrong DeclaringType in the returned method.
Also refer to Mono.Cecil test ImportCecilTests.ImportGenericMethod(). The test also uses an extension MakeGeneric which creates a new GenericInstanceType for the MethodReference.DeclaringType.
When doing the same in the PropertyChanged-solution, other unit test failed, so I just left it in FindNamedMethod.

Fix #259: Exception for properties referencing a generic type with equality comparers in another assembly

---

PropertyChanged.Fody/EventArgsCache.cs
PropertyChanged.Fody/EventArgsCacheInjector.cs
PropertyChanged.Fody/InstructionListExtensions.cs
PropertyChanged.Fody/MethodFinder.cs
PropertyChanged.Fody/MethodInjector.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/MsCoreReferenceFinder.cs
PropertyChanged.Fody/PropertyWeaver.cs
Tests/AssemblyToProcessTests.cs
Tests/MethodFinderTest.cs

This PR aims to eliminate heap allocations when property change events are raised, as those tend to pile up in big projects. This should bring an overall performance improvement by reducing the time spent in GC.
This is achieved by injecting a static internal class named `<>PropertyChangedEventArgs` which has fields of `PropertyChangedEventArgs` instances. This is safe as `PropertyChangedEventArgs` is immutable. There is one field per distinct property name (if several classes have a `Foo` property, only one `Foo` event args field will be generated).
To support this, when an event invoker needs to be injected, this will inject a method with the  `void OnPropertyChanged(PropertyChangedEventArgs)` signature instead of `void OnPropertyChanged(string)`.
When multiple suitable event invoker …

Reduce GC pressure

---

PropertyChanged.Fody/MethodInjector.cs
Tests/MethodInjectorTests.cs

This fixes an issue I've encountered: one of my classes implemented `INotifyPropertyChanged` but also had an additional `PropertyChangedEventHandler` field, which caused the `SingleOrDefault` in the original code to throw with an unhelpful error message.
This PR changes the field detection logic: it chooses the correct field based on the `add_PropertyChanged` IL, which lets you have multiple `PropertyChangedEventHandler` in a class.

Fix exception when there are multiple event handler fields

---

PropertyChanged.Fody/MethodInjector.cs
README.md

This is something that got me thinking since my previous PR: I don't think injected methods should be exposed to the outside world, for several reasons:
- Foreign code has no business calling `OnPropertyChanged` on a different class.
- People shouldn't extend weaved classes and make use of injected methods, as it seems very brittle, and the development workflow would be... weird at best. I really hope no one actually relies on this.
- If someone really _needs_ to expose an event invoker for some reason, he should declare it by himself and not rely on injection, to ensure API stability. Plus, it makes for a better workflow than the previous point.
- #318 already made a breaking change by changing the signature of the default injected method anyway.
So, this PR changes the injected method …

Don't expose injected methods

---

PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/PropertyData.cs
PropertyChanged.Fody/TypeEqualityFinder.cs
PropertyChanged.Fody/UseStaticEqualsFromBaseConfig.cs
TestAssemblies/AssemblyWithBase/StaticEquals/BaseClass.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/BaseClass.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/BaseClass2.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/BaseClass3.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/ClassUsingBase.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/ClassWithOwnEquals.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/ClassWithTwoBaseClasses1.cs
TestAssemblies/AssemblyWithBase/StaticEqualsGenericParent/ClassWithTwoBaseClasses2.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEquals/StaticEquals.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEqualsGenericParent/ArgsMapping1.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEqualsGenericParent/ArgsMapping2.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEqualsGenericParent/OwnStaticEquals.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEqualsGenericParent/StaticEquals.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/StaticEqualsGenericParent/StaticEqualsOnBase.cs
Tests/AssemblyWithBaseInDifferentModuleTests.cs

#309: static Equals not used

---

PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/NotifyInterfaceFinder.cs
PropertyChanged.Fody/TypeEqualityFinder.cs

e.g. because they are defined in a mixed-mode assembly.

Fix #329: Ignore base types that can't be resolved

---

PropertyChanged.Fody/TypeEqualityFinder.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/Hierarchy/ChildClass.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/Hierarchy/StaticEquals.cs
Tests/AssemblyWithBaseInDifferentModuleTests.cs

In my last PR (#310) I've introduced a bug:
Equality comparers in class hierarchies are not properly detected, as the child nodes of NotifyNodes weren't processed.
Here the fix for it.

Equality comparers not detected in class hierarchies

---

PropertyChanged.Fody/EventInvokerNameResolver.cs
Tests/EventInvokerNamesConfigTests.cs

The issue arises when a base class in a different project gets its event invoker injected.
Derived classes in different projects didn't recognize the method as the event invoker.
This commit makes sure the injected event invoker method is always included in the list of methods to consider.
Detailed issue description [here](https://github.com/Fody/PropertyChanged/issues/333#issuecomment-381766005).
This closes #333 and _maybe_ even #316 .

Fix the injected invoker name not being recognized

---

PropertyChanged.Fody/CecilExtensions.cs
PropertyChanged.Fody/EventInvokerNameResolver.cs
PropertyChanged.Fody/MethodFinder.cs
TestAssemblies/AssemblyToProcess/SupportedLibraries/BaseClasses.cs
TestAssemblies/AssemblyToProcess/SupportedLibraries/ClassReactiveUI.cs
Tests/AssemblyToProcessTests.cs
Tests/EventInvokerNamesConfigTests.cs

This PR adds support for explicit interface implementations to PropertyChanged.Fody. The current behavior is, that if Fody finds a method that is hidden from derived classes, it begins to panic and says: `Cannot use '{MethodReference.FullName}' in '{TypeDefinition.FullName}' since that method is not visible from the child class.`
Due to this, one could hardly use this awesome library with [ReactiveUI MVVM framework](https://github.com/reactiveui/ReactiveUI/blob/74b25861184ce59f2e1e890efa0faf2324991d45/src/ReactiveUI/ReactiveObject.cs#L67) - ReactiveUI's [ReactiveObject](https://github.com/reactiveui/ReactiveUI/blob/74b25861184ce59f2e1e890efa0faf2324991d45/src/ReactiveUI/ReactiveObject.cs#L62) uses explicit interface implementation, RaisePropertyChanged method is hidden:
```csharp
public …
```

Support for explicit interface implementations

---

PropertyChanged.Fody/MethodInjector.cs
PropertyChanged.Fody/PropertyChangedAddMethodFinder.cs
Tests/MethodInjectorTests.cs

I believe a *subtle* regression has been introduced in 8465c68: when there is an explicit event implementation, then an additional `PropertyChanged` event should be ignored.
Yeah, that's a *totally* implausible edge case, but here's the fix anyway (don't even bother to do a release just for that one).

Fix GetPropertyChangedAddMethods logic

---

PropertyChanged/FilterTypeAttribute.cs
TestAssemblies/AssemblyWithTypeFilter/AssemblyInfo.cs
TestAssemblies/AssemblyWithTypeFilter/TestClassIncludeAlso.cs
Tests/TypeFilterTests.cs

Docs say
> To scope the rewriting only to specific classes, and not the whole Assembly, you can use the FilterType attribute. This changes the general behavior from from opt-out to opt-in. Example: [assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")]. The string is interpreted as a Regex, and you can use **multiple** filters. A class will be weaved, if any filter matches.
This is not possible if AllowMultiple is not set to true for FilterTypeAttribute, which this pull request does.

Set AllowMultiple = true for FilterTypeAttribute

---

PropertyChanged.Fody/CollectionCustomAttributeExtension.cs
PropertyChanged.Fody/EventArgsCache.cs
PropertyChanged.Fody/MethodInjector.cs
PropertyChanged.Fody/MsCoreReferenceFinder.cs

Where it is clear the below content has not read, the issue is likely to be closed with "please read the template". Please don't take offense at this. It is simply a time management decision. When someone raises an issue, without reading the template, then often too much time is spent going back and forth to obtain information that is outlined below.
To be using Fody you should be a [Patron](https://opencollective.com/fody/order/3059). See [Licensing/Patron FAQ](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md). With that in mind, it is assumed anyone raising a PR is already a Patron. As such your GitHub Id may be verified against the [OpenCollective contributors](https://opencollective.com/fody#contributors). This process will depend on the PR quality, your …

Add GeneratedCodeAttribute and DebuggerNonUserCodeAttribute to the generated <>OnPropertyChanged method

---

PropertyChanged.Fody/MethodInjector.cs

(copied from #473)
**TL;DR**: Having PropertyChanged event declared as abstract causes NRE in `ModuleWeaver.GetEventHandlerField()` due to `addMethods.Single().Body.Instructions` being null.
___
**Long story**: here's the minimal setup to reproduce the bug:
``` C#
abstract class BaseClass : INotifyPropertyChanged
{
public abstract event PropertyChangedEventHandler PropertyChanged;
}
```
I understand that such setup is very uncommon, and I've even run into it by mistake. But then I've spent a few hours debugging the issue, because the actual crash doesn't reveal much of useful info:
```
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\user\source\repos\FodyTest\packages\PropertyChanged.Fody.3.1.3\ …
```

explicitly throw exception if PropertyChange event is abstract

---

PropertyChanged.Fody/AttributeCleaner.cs
PropertyChanged.Fody/Config/SuppressWarningsConfig.cs
PropertyChanged.Fody/EqualityCheckWeaver.cs
PropertyChanged.Fody/IsChangedMethodFinder.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/NotifyInterfaceFinder.cs
PropertyChanged.Fody/OnChangedWalker.cs
PropertyChanged.Fody/TypeEqualityFinder.cs
PropertyChanged.Fody/WarningChecker.cs
PropertyChanged.sln
PropertyChanged/SuppressPropertyChangedWarningsAttribute.cs
TestAssemblies/AssemblyToProcess/ClassWithInvalidOnChanged.cs
TestAssemblies/AssemblyWithStaticOnPropertyNameChanged/AssemblyWithStaticOnPropertyNameChanged.csproj
TestAssemblies/AssemblyWithStaticOnPropertyNameChanged/ClassWithNonVoidOnPropertyChanged.cs
Tests/AssemblyToProcessTests.cs
Tests/InjectOnPropertyNameChangedTests.cs
Tests/SuppressWarningsConfigTests.cs
Tests/Tests.csproj

This is a POC for #447. It's completely up for debate.
This PR adds warnings for invalid usages of `On_PropertyName_Changed` methods:
- A method with an unexpected signature is found
- No matching property is found, or the matching property does not get processed
It additionally adds an `[SuppressPropertyChangedWarnings]` attribute to let the user suppress these warnings, and a `SuppressWarnings` config attribute to suppress all warnings (in case you have a codebase where this change would trigger false positives for some reason).
Some other points for consideration:
- Currently a non-void `On_PropertyName_Changed` method will cause an error. Should that be replaced with a warning (and ignoring the method)?
- Currently static `On_PropertyName_Changed` methods are simply ignored. Should …

Add warnings for invalid On_PropertyName_Changed methods

---

PropertyChanged.Fody/MethodFinder.cs
PropertyChanged.Fody/MethodGenerifier.cs
TestAssemblies/AssemblyToProcess/GenericMiddle/ClassWithGenericMiddle.cs
TestAssemblies/AssemblyToProcess/GenericMiddle/ClassWithGenericMiddleBase.cs
TestAssemblies/AssemblyToProcess/GenericMiddle/ClassWithGenericMiddleChild.cs
TestAssemblies/AssemblyWithBase/GenericMiddle/BaseClassWithGenericMiddle.cs
TestAssemblies/AssemblyWithBase/GenericMiddle/BaseClassWithGenericMiddleBase.cs
TestAssemblies/AssemblyWithBaseInDifferentModule/GenericMiddle/ClassWithGenericMiddleChildInDifferentModule.cs
Tests/AssemblyToProcessTests.cs
Tests/AssemblyWithBaseInDifferentModuleTests.cs

Fixes #477
This is a WIP as I found a similar problem happens when the base class is in a different assembly (a totally different code path is used in that case). I didn't fix it yet as I'm not really sure about the correct way to do this.

Fix references to event invokers when a generic class is in the inheritance chain

---

PropertyChanged.Fody/MethodFinder.cs

This fixes #508
The problem is I could not replicate the issue without having the test assembly use an external reference to the ReactiveUI library.

Call explicit interface methods correctly

---

PropertyChanged.Fody/Config/SuppressOnPropertyNameChangedWarningConfig.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/OnChangedWalker.cs
PropertyChanged.Fody/PropertyChanged.Fody.xcf
PropertyChanged.Fody/WarningChecker.cs
SmokeTest/FodyWeavers.xsd
Tests/SuppressOnPropertyNameChangedWarningConfigTests.cs

This PR fixes the missing config schema for `SuppressWarnings`
This PR adds a new config `SuppressOnPropertyNameChanged`
Fixes #539

Suppress on property name changed config

---

PropertyChanged.Fody/DependsOnDataAttributeReader.cs
PropertyChanged.Fody/IlGeneratedByDependencyReader.cs
TestAssemblies/AssemblyToProcess/ClassWithIndexerDependsOnAndBeforeAfter.cs
TestAssemblies/AssemblyToProcess/ClassWithIndexerReferencingPropertyAndBeforeAfter.cs
Tests/AssemblyToProcessTests.cs

Fixes #544 by ignoring indexers in dependency resolution. Also Ignores `[DependsOn]` on indexers.

Ignore indexer dependencies

---

PropertyChanged.Fody/MappingFinder.cs
TestAssemblies/AssemblyToProcess/ClassWithNullableBackingField.cs
Tests/AssemblyToProcessTests.cs

This is the same change as in https://github.com/Fody/PropertyChanging/pull/160
A similar issue to https://github.com/Fody/PropertyChanging/pull/156 exists here, but instead of producing an invalid program, the equality check was skipped.

Limit field mapping to fields of the same type as the property

---

PropertyChanged.Fody/Config/EnableIsChangedPropertyConfig.cs
PropertyChanged.Fody/Config/TriggerDependentPropertiesConfig.cs
PropertyChanged.Fody/IlGeneratedByDependencyProcessor.cs
PropertyChanged.Fody/ModuleWeaver.cs
PropertyChanged.Fody/PropertyChanged.Fody.xcf
PropertyChanged.Fody/PropertyWeaver.cs
PropertyChanged.sln
SmokeTest/FodyWeavers.xsd
TestAssemblies/AssemblyWithDisabledIsChangedProperty/AssemblyWithDisabledIsChangedProperty.csproj
TestAssemblies/AssemblyWithDisabledIsChangedProperty/IsChangedClassToTest.cs
TestAssemblies/AssemblyWithDisabledTriggerDependentProperties/AssemblyWithDisabledTriggerDependentProperties.csproj
TestAssemblies/AssemblyWithDisabledTriggerDependentProperties/DependentPropertiesClassToTest.cs
Tests/AssemblyWithDisabledIsChangedPropertyTests.cs
Tests/AssemblyWithDisabledTriggerDependentPropertiesTests.cs
Tests/Tests.csproj
Tests/TriggerDependentPropertiesConfigTests.cs

Added an option **TriggerDependentProperties** to the weavers.xml file, set to false will disable the dependency processor.
`<PropertyChanged TriggerDependentProperties='false'/>`

Add an option to disable automatic dependent property changed. #282

---

PropertyChanged.Fody/OnChangedMethod.cs
PropertyChanged.Fody/OnChangedWalker.cs
PropertyChanged.Fody/PropertyData.cs
PropertyChanged.Fody/PropertyWeaver.cs
PropertyChanged.Fody/TypeNode.cs
TestAssemblies/AssemblyToProcess/ClassWithDependsOnAndPropertyChanged.cs
TestAssemblies/AssemblyToProcess/ClassWithInvalidOnChanged.cs
TestAssemblies/AssemblyToProcess/ClassWithOnChangedBeforeAfterCalculatedProperty.cs
TestAssemblies/AssemblyToProcess/ClassWithOnChangedCalculatedProperty.cs
TestAssemblies/AssemblyToProcess/ClassWithWarnings.cs
Tests/AssemblyToProcessTests.cs
Tests/AssemblyWithInheritanceTests.cs

Hi, new Patron here, just signed up.  Also I've used SVN most of my software dev career so completely new to git/github so go easy if I haven't done something quite right.
The 3.2.0 release introduced a bug whereby calculated properties would no longer raise an On-Property-Changed() call, so for example:
```
public string Property1 { get; set; }
public string Property2 => $"{Property1}!";
public void OnProperty2Changed() => Console.WriteLine("Property 2 has changed");
```
OnProperty2Changed() is no longer called, despite OnPropertyChanged being raised for Property2;
3.2.0 moved storage of OnChangedMethods from TypeNode to TypeNode.PropertyData, which is problematic because this collection only contains those properties which are to have their setters modified.  As a calculated property …

On-PropName-Changed not called for dependent properties Fixes #700

---

PropertyChanged.Fody/PropertyDataWalker.cs
TestAssemblies/AssemblyToProcess/ClassWithDoNotNotifyField.cs
Tests/AssemblyToProcessTests.cs

This skips a property if its backing field is marked as `[DoNotNotify]`.
This attribute can target fields, but the weaver currently ignores that. We should either add support (which this PR does), or remove the field target for consistency. I'm not sure which option is better, but since the change is trivial and helps someone, I figured why not just support this? 🙂 
Closes #846

Support [DoNotNotify] on fields

---

PropertyChanged.Fody/CecilExtensions.cs
PropertyChanged.Fody/MethodInjector.cs
PropertyChanged.Fody/PropertyWeaver.cs
PropertyChanged/AddINotifyPropertyChangedInterfaceAttribute.cs
TestAssemblies/AssemblyToProcess/StructWithNotify.cs
Tests/AssemblyToProcessTests.cs
Tests/EventTester.cs

This fixes the codegen for value types by boxing the instance where needed.
I also allowed `[AddINotifyPropertyChangedInterface]` on structs, as it seemed the right thing to do. Note that this case is always handled by the weaver. The source generator doesn't handle it since that generates [CS0282](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0282) and the user would need to disable it in their code.
Fixes #901

Fix codegen for value types

---

PropertyChanged.Fody.Analyzer.Tests/PropertyChanged.Fody.Analyzer.Tests.csproj
PropertyChanged.Fody.Analyzer/PropertyChanged.Fody.Analyzer.csproj

This follows my remark from [here](https://github.com/Fody/PropertyChanged/pull/1052#discussion_r1566529798):
> Oh, I didn't notice this earlier, but I think the Microsoft.CodeAnalysis.CSharp package should be rolled back to v4.0.1 and frozen at that version unless there's a good reason to use a newer one, since referencing a newer version requires the user to have a .NET SDK or Visual Studio version which supports it. See [here](https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md?rgh-link-date=2024-04-15T23%3A14%3A06Z) for the version map.
> 
> The problem is that it won't play along with tools which always suggest to bump the packages to the latest versions. 😞
So this ensures the analyzer supports older compilers, but runs tests with the latest one. Contrary to my …

Reference fixed Roslyn version
